### ISSUE TITLE
Mudança de nome do repositório

### ISSUE THREAD

**Issue by marcelino05052000** [ifpe-cti/demo-project-amriel#2]
Professor @fabriciofx , preciso que o senhor altere o nome do projeto, já que mudamos o nome para "Demo Project Amriel". Preciso que altere de "demo-lone-survivor" para "demo-project-amriel". Não tenho o direito de mudar isso, pois o senhor é o novo proprietário do repositório. Agradeço desde já, qualquer coisa, pergunte.

**Comment by viniciussoaresti** [comment]
@marcelino05052000 Quem era o antigo dono do repositório? No caso do gráfica, era meu, e continuei com os privilégios como Arquiteto. Não sei se isso foi do próprio github, ou prof. @fabriciofx que configurou, mas vale o teste.

**Comment by viniciussoaresti** [comment]
@marcelino05052000 Por exemplo, baseado na sua decisão, mudei o nome do nosso, desde que tenho as permissões. É o primeiro item das configurações do repositório.

**Comment by viniciussoaresti** [comment]
@Jnsb não tem permissão não, @marcelino05052000 ? Ou @nadsonc ?

**Comment by marcelino05052000** [comment]
tem não

**Comment by fabriciofx** [comment]
@marcelino05052000 Desculpe a demora. Mas:

1. Renomei o nome do repositório, conforme solicitado
2. Coloquei você com permissão de `Admin` no repositório. Portanto, cuidado com o que faz nele!

Ademais, uma observação: já estamos em maio/2018 e até agora não vi nada com relação ao seu projeto aqui no repositório. Pelo que eu já vi de grupos anteriores do PPO, isso é um mau sinal, uma vez que os grupos que foram nessa caminho, acabaram abandonando ou reprovando o PPO. Assim, se permites uma sugestão, *faça upload do que você tiver do seu projeto, urgentemente!*

**Comment by marcelino05052000** [comment]
Ok, farei isso. Fecharei está issue agora, já que o problema foi resolvido. Obrigado.
