### ISSUE TITLE
Atualizar sprites que não tem fundo transparente

### ISSUE THREAD

**Issue by marcelino05052000** [ifpe-cti/demo-project-amriel#5]
@Jnsb , por favor, atualize os sprites "arvore" e "arbusto", assim como algum outro com fundo, para deixar com fundo transparente. A imagem do cenário está muito feia com essas cores atrás.

**Comment by Jnsb** [comment]
Atualizado com sucesso.

**Comment by marcelino05052000** [comment]
ok
